spring.application.name=factory-microservice

auth-microservice.url=http://auth-microservice:8081
basic-microservice.url=http://basic-microservice:8080

auth-microservice.user=user
auth-microservice.pass=qwertyui